#!/bin/bash
clamav-unofficial-sigs.sh
_now=$(date +"%m_%d_%Y")
clamscan --recursive --infected --exclude-dir='^/sys|^/dev|^/proc|^/var/lib/clamav' --max-filesize=4000M --max-scansize=4000M / -l ~/clamav-scan-results/scan$_now